/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room2.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
	const group = useRef()
	const { nodes, materials, animations } = useGLTF('/room2.glb')
	const { actions } = useAnimations(animations, group)
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<mesh
					name='SillaAsiento001'
					geometry={nodes.SillaAsiento001.geometry}
					material={nodes.SillaAsiento001.material}
					position={[-1.2, 0.56, -0.84]}
					rotation={[-Math.PI, 0.98, -Math.PI]}
				/>
				<mesh
					name='SillaEstructura001'
					geometry={nodes.SillaEstructura001.geometry}
					material={nodes.SillaEstructura001.material}
					position={[-1.36, 0.8, -0.75]}
					rotation={[-Math.PI, 0.98, -Math.PI]}
				/>
				<mesh
					name='SillaEspaldar001'
					geometry={nodes.SillaEspaldar001.geometry}
					material={nodes.SillaEspaldar001.material}
					position={[-1.34, 0.8, -0.76]}
					rotation={[-Math.PI, 0.98, -Math.PI]}
				/>
				<mesh
					name='teeth001'
					geometry={nodes.teeth001.geometry}
					material={nodes.teeth001.material}
					position={[-0.06, 1.02, -1.33]}
					rotation={[-0.17, 0, 0]}
				/>
				<mesh
					name='mouth001'
					geometry={nodes.mouth001.geometry}
					material={nodes.mouth001.material}
					position={[-0.06, 1.02, -1.35]}
					rotation={[-0.17, 0, 0]}
				/>
				<mesh
					name='room'
					geometry={nodes.room.geometry}
					material={nodes.room.material}
					position={[0.79, 0.82, -1.41]}
					rotation={[0, 1.57, 0]}
				/>
				<mesh
					name='vidrioEntorno'
					geometry={nodes.vidrioEntorno.geometry}
					material={nodes.vidrioEntorno.material}
					position={[-1.86, 1.81, 0.09]}
				/>
				<mesh
					name='piso'
					geometry={nodes.piso.geometry}
					material={nodes.piso.material}
					position={[0.08, 0, 0.08]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh
					name='vidrioCPU'
					geometry={nodes.vidrioCPU.geometry}
					material={nodes.vidrioCPU.material}
					position={[-0.63, 0.73, -1.46]}
				/>
				<mesh
					name='venom'
					geometry={nodes.venom.geometry}
					material={nodes.venom.material}
					position={[-0.06, 1.04, -1.38]}
					rotation={[-0.17, 0, 0]}
				/>
				<mesh
					name='monitorInteractivo'
					geometry={nodes.monitorInteractivo.geometry}
					material={nodes.monitorInteractivo.material}
					position={[-1.18, 1.07, -1.37]}
				/>
				<mesh
					name='cortinon'
					geometry={nodes.cortinon.geometry}
					material={nodes.cortinon.material}
					position={[-1.71, 1.55, 0.09]}
					rotation={[0, 0, -1.52]}
				/>
				<mesh
					name='ledFrontal'
					geometry={nodes.ledFrontal.geometry}
					material={nodes.ledFrontal.material}
					position={[-0.62, 0.84, -1.21]}
				/>
				<mesh
					name='aroTrasero'
					geometry={nodes.aroTrasero.geometry}
					material={nodes.aroTrasero.material}
					position={[-0.55, 0.85, -1.67]}
				/>
				<mesh
					name='aroSuperior2'
					geometry={nodes.aroSuperior2.geometry}
					material={nodes.aroSuperior2.material}
					position={[-0.54, 0.96, -1.4]}
				/>
				<mesh
					name='aroSuperior1'
					geometry={nodes.aroSuperior1.geometry}
					material={nodes.aroSuperior1.material}
					position={[-0.54, 0.96, -1.54]}
				/>
				<mesh
					name='aroFrontal3'
					geometry={nodes.aroFrontal3.geometry}
					material={nodes.aroFrontal3.material}
					position={[-0.52, 0.58, -1.23]}
				/>
				<mesh
					name='aroFrontal2'
					geometry={nodes.aroFrontal2.geometry}
					material={nodes.aroFrontal2.material}
					position={[-0.52, 0.71, -1.23]}
				/>
				<mesh
					name='aroFrontal1'
					geometry={nodes.aroFrontal1.geometry}
					material={nodes.aroFrontal1.material}
					position={[-0.52, 0.84, -1.23]}
				/>
				<mesh
					name='ledCPU'
					geometry={nodes.ledCPU.geometry}
					material={nodes.ledCPU.material}
					position={[-0.61, 0.71, -1.68]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<mesh
					name='ledEscritorio'
					geometry={nodes.ledEscritorio.geometry}
					material={nodes.ledEscritorio.material}
					position={[-1.2, 1.14, -1.58]}
				/>
				<mesh
					name='luzTeclas'
					geometry={nodes.luzTeclas.geometry}
					material={nodes.luzTeclas.material}
					position={[-1.2, 0.96, -1.31]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
				/>
			</group>
		</group>
	)
}

useGLTF.preload('/room2.glb')
